services:
  bot:
    image: webdev-bot:latest
    build:
      context: .
      target: production
      args:
        NODE_VERSION: ${NODE_VERSION}
    container_name: webdev-bot
    restart: unless-stopped
    depends_on:
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/db.sqlite
    volumes:
      - ./.env.production:/app/.env.production:ro
      - guides-data:/app/data

  migrate:
    image: webdev-bot:latest
    environment:
      - DATABASE_URL=file:/app/data/db.sqlite
    env_file:
      - .env
    command: ['pnpm', 'run', 'migrate:deploy']
    restart: 'no'
    volumes:
      - guides-data:/app/data
    user: 'node'

volumes:
  guides-data:
    driver: local
